### ISSUE TITLE
Delivery receipt transit: IllegalArgumentException

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#169]
We need to fix bugs:

(we need to refactor the way how we update a DLR message - usage of "createDeliveryReceiptMessage()" changes data too unexpectably)

1)  stat: changed UNDL -> EXPIRED

2)
2017-02-14 02:14:08,806 ERROR [javax.slee.SbbNotification[service=ServiceID[name=SmscTxSmppServerService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=TxSmppServerSbb,vendor=org.mobicents,version=1.0]].TxSmppServerSbbImpl] (SLEE-EventRouterExecutor-1-thread-1) Exception when processing SubmitSm message: The '27' is not a valid value!
java.lang.IllegalArgumentException: The '27' is not a valid value!
	at org.mobicents.smsc.library.ErrorCode.fromInt(ErrorCode.java:397)
	at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.processSms(TxSmppServerSbb.java:1634)
	at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.onDeliverSm(TxSmppServerSbb.java:639)
	at sun.reflect.GeneratedMethodAccessor429.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128)
	at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
This issue is doubled:
https://github.com/RestComm/smscgateway/issues/194
