### ISSUE TITLE
CdrGenerator - java.lang.NullPointerException

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#175]
We need to fix the issue:

2017-02-21 06:25:57,046 ERROR [javax.slee.SbbNotification[service=ServiceID[name=SmscRxSmppServerService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=RxSmpp
ServerSbb,vendor=org.mobicents,version=1.0]].RxSmppServerSbb] (SLEE-EventRouterExecutor-5-thread-1) Exception in RxSmppServerSbb.onDeliverSmResp() when fetching
 records and issuing events: null
java.lang.NullPointerException
        at org.mobicents.smsc.library.CdrGenerator.generateCdr(CdrGenerator.java:136)
        at org.mobicents.smsc.slee.services.deliverysbb.DeliveryCommonSbb.generateCDR(DeliveryCommonSbb.java:1415)
        at org.mobicents.smsc.slee.services.smpp.server.rx.RxSmppServerSbb.handleResponse(RxSmppServerSbb.java:597)
        at org.mobicents.smsc.slee.services.smpp.server.rx.RxSmppServerSbb.onSubmitSmResp(RxSmppServerSbb.java:196)
        at sun.reflect.GeneratedMethodAccessor295.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
        at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381)
        at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128)
        at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by faizann** [comment]
That is my code. I can fix it

**Comment by vetss** [comment]
@faizann 

we need to replace :
.append(smsEvent.getSmsSet().getSms(0).getMtServiceCenterAddress())
->
.append(smsEvent.getMtServiceCenterAddress())

**Comment by vetss** [comment]
Extra optimization comment:

We need to replace 
- segmList.segmList
- SmsSetCache.lstSmsSetInProcessing

from FastMap to a thread-safe collection

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/smscgateway/commit/eeae5fdeb4f75bbb108c28f897a24f55918d091d
