### ISSUE TITLE
Exception when creating of createDeliveryReceiptMessage() in TxSbb

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#194]
2017-04-11 20:22:25,786 ERROR [javax.slee.SbbNotification[service=ServiceID[name=SmscTxSmppServerService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=TxSmppServerSbb,vendor=org.mobicents,version=1.0]].TxSmppServerSbb] (SLEE-EventRouterExecutor-1-thread-1) Exception when 
processing SubmitSm message: The '502' is not a valid value! 
java.lang.IllegalArgumentException: The '502' is not a valid value! 
at org.mobicents.smsc.library.ErrorCode.fromInt(ErrorCode.java:397) 
at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.processSms(TxSmppServerSbb.java:1325) 
at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.onDeliverSm(TxSmppServerSbb.java:594) 
at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479) 
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381) 
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128) 
at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/6d8f41e5f56736d05a5badf1fb05f4bcea18984d
