### ISSUE TITLE
Cases for changing of logging ERROR->WARN

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#212]
We have some logging examples that are needed to change of logging level ERROR->WARN. Let's put into the issue such examples so we can further fix them.

**Comment by vetss** [comment]
2017-05-10 06:25:03,727 INFO [com.cloudhopper.smpp.impl.DefaultSmppSession] (SLEE-EventRouterExecutor-51-thread-1) ---- - sendResponsePdu() - after channel.write() SLEE-EventRouterExecutor-51-thread-1 (submit_sm_resp: 0x00000033 0x80000004 0x0000000B 0x00000240 result: "Dest address invalid") (body: (messageId [])) (opts: (additional_status_info: 0x001D 0x001E [4465737441646472657373206469676974732061726520616273656E7400])) 
2017-05-10 06:25:03,729 INFO [javax.slee.SbbNotification[service=ServiceID[name=SmscTxSmppServerService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=TxSmppServerSbb,vendor=org.mobicents,version=1.0]].TxSmppServerSbb] (SLEE-EventRouterExecutor-16-thread-1) ***** smpp_in_smsc : Received SUBMIT_SM = (submit_sm: 0x000000B7 0x00000004 0x00000000 0x00000244) (body: (serviceType [CMT] sourceAddr [0x05 0x00 [xxxxxxx]] destAddr [0x01 0x01 []] esmCls [0x00] regDlvry [0x00] dcs [0x08] message [*************])) (opts: (sar_msg_ref_num: 0x020C 0x0002 [573D]) (sar_total_segments: 0x020E 0x0001 [04]) (sar_segment_seqnum: 0x020F 0x0001 [02])) from Esme name=Simah_TRX_3 
2017-05-10 06:25:03,729 ERROR [javax.slee.SbbNotification[service=ServiceID[name=SmscTxSmppServerService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=TxSmppServerSbb,vendor=org.mobicents,version=1.0]].TxSmppServerSbb] (SLEE-EventRouterExecutor-16-thread-1) DestAddress digits are absent 
org.mobicents.smsc.library.SmscProcessingException: DestAddress digits are absent 
at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.createDestTargetAddress(TxSmppServerSbb.java:1443) 
at org.mobicents.smsc.slee.services.smpp.server.tx.TxSmppServerSbb.onSubmitSm(TxSmppServerSbb.java:218) 
at sun.reflect.GeneratedMethodAccessor285.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:606) 
at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479) 
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381) 
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128) 
at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/smscgateway/commit/181a4c1502e5a9bc048ac611921834cf0e81b28e
