### ISSUE TITLE
HR transparent mode error

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#242]
We need to fix an error for the case when we are working in transactional mode and getting messages from  MO and HR procedure.

2017-07-11 04:42:24,039 ERROR [javax.slee.SbbNotification[service=ServiceID[name=MoService,vendor=org.mobicents,version=1.0],sbb=SbbID[name=MoSbb,vendor=org.mobicents,version=1.0]].MoSbb] (SLEE-EventRouterExecutor-1-thread-1) Error while sending ForwardShortMessageResponse 
 org.mobicents.protocols.ss7.map.api.MAPException: Bad application context name for addForwardShortMessageResponse: must be shortMsgMORelayContext_V1 or V2 or shortMsgMTRelayContext_V1 or V2
 at org.mobicents.protocols.ss7.map.service.sms.MAPDialogSmsImpl.addForwardShortMessageResponse(MAPDialogSmsImpl.java:128)
 at org.mobicents.slee.resource.map.service.sms.wrappers.MAPDialogSmsWrapper.addForwardShortMessageResponse(MAPDialogSmsWrapper.java:90)
 at org.mobicents.smsc.slee.services.mo.MessageDeliveryResultResponseMo.responseDeliverySuccess(MessageDeliveryResultResponseMo.java:73)
 at org.mobicents.smsc.slee.services.deliverysbb.DeliveryCommonSbb.sendTransactionalResponseSuccess(DeliveryCommonSbb.java:840)
 at org.mobicents.smsc.slee.services.smpp.server.rx.RxSmppServerSbb.handleResponse(RxSmppServerSbb.java:831)
 at org.mobicents.smsc.slee.services.smpp.server.rx.RxSmppServerSbb.onSubmitSmRespParentLocal(RxSmppServerSbb.java:301)
 at org.mobicents.smsc.slee.services.smpp.server.rx.RxSmppServerSbb.onSubmitSmRespParent(RxSmppServerSbb.java:193)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:606)
 at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
 at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381)
 at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128)
 at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
 at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/137c1eb8aaff47d0674cdbc305eff6f80ca5c80a
