### ISSUE TITLE
Failure invoking smsc services jar file

### ISSUE THREAD

**Issue by MaabSaleeem** [RestComm/smscgateway#278]
Hi. Why am I receiving this error when I start the server? The file exists but it isn't getting deployed

17:06:40,347 INFO  [PreferredPackagesBuilder] (SLEE-InternalDeployer-thread-1) No preferred package entry found. Applying defaults.
17:06:40,410 ERROR [DeploymentManager] (SLEE-InternalDeployer-thread-1) Failure invoking 'InstallDeployableUnitAction[file:/opt/restcomm-smsc-7.3.153/jboss-5.1.0.GA/server/simulator/deploy/smsc-services-du-7.3.153.jar/]
javax.slee.management.DeploymentException: Failure encountered during deploy process.
	at org.mobicents.slee.container.management.jmx.DeploymentMBeanImpl.install(DeploymentMBeanImpl.java:340)
	at org.mobicents.slee.container.deployment.jboss.action.InstallDeployableUnitAction.invoke(InstallDeployableUnitAction.java:41)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.sciAction(DeploymentManager.java:316)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.installDeployableUnit(DeploymentManager.java:181)
	at org.mobicents.slee.container.deployment.jboss.SLEESubDeployer.start(SLEESubDeployer.java:281)
	at org.mobicents.slee.container.deployment.jboss.SleeContainerDeployerImpl.start(SleeContainerDeployerImpl.java:271)
	at org.mobicents.slee.container.deployment.jboss.SLEEDeployer.callSubDeployer(SLEEDeployer.java:124)
	at org.mobicents.slee.container.deployment.jboss.SLEEDeployer.setInternalDeployer(SLEEDeployer.java:170)
	at org.mobicents.slee.container.deployment.jboss.SleeContainerDeployerImpl$1.run(SleeContainerDeployerImpl.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.slee.management.DeploymentException: failed to build deployable unit
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.build(DeployableUnitBuilderImpl.java:295)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.build(DeployableUnitBuilderImpl.java:72)
	at org.mobicents.slee.container.management.jmx.DeploymentMBeanImpl.install(DeploymentMBeanImpl.java:164)
	... 13 more
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 15
	at javassist.CtClassType.getClassFile2(CtClassType.java:203)
	at javassist.CtClassType.getInterfaces(CtClassType.java:630)
	at org.mobicents.slee.container.component.deployment.SbbAbstractClassDecorator$1.edit(SbbAbstractClassDecorator.java:204)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:191)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
	at javassist.CtBehavior.instrument(CtBehavior.java:618)
	at org.mobicents.slee.container.component.deployment.SbbAbstractClassDecorator.trapMethodIfENCBindCall(SbbAbstractClassDecorator.java:193)
	at org.mobicents.slee.container.component.deployment.SbbAbstractClassDecorator.decorateENCBindCalls(SbbAbstractClassDecorator.java:182)
	at org.mobicents.slee.container.component.deployment.SbbAbstractClassDecorator.decorateAbstractSbb(SbbAbstractClassDecorator.java:124)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.loadAndSetNonGeneratedComponentClasses(DeployableUnitBuilderImpl.java:479)
	at org.mobicents.slee.container.component.deployment.DeployableUnitBuilderImpl.build(DeployableUnitBuilderImpl.java:236)
	... 15 more
Caused by: java.io.IOException: invalid constant type: 15
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1027)
	at javassist.bytecode.ConstPool.read(ConstPool.java:970)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
	at javassist.bytecode.ClassFile.read(ClassFile.java:693)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
	at javassist.CtClassType.getClassFile2(CtClassType.java:190)
	... 25 more
17:06:40,661 ERROR [SLEESubDeployer] (SLEE-InternalDeployer-thread-1) 
javax.slee.UnrecognizedServiceException: Unrecognized service ServiceID[name=MoService,vendor=org.mobicents,version=1.0]
	at org.mobicents.slee.container.management.ServiceManagementImpl.activate(ServiceManagementImpl.java:242)
	at org.mobicents.slee.container.management.ServiceManagementImpl.activate(ServiceManagementImpl.java:223)
	at org.mobicents.slee.container.deployment.jboss.action.ActivateServiceAction.invoke(ActivateServiceAction.java:59)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.sciAction(DeploymentManager.java:316)
	at org.mobicents.slee.container.deployment.jboss.DeploymentManager.installDeployableUnit(DeploymentManager.java:181)
	at org.mobicents.slee.container.deployment.jboss.SLEESubDeployer.start(SLEESubDeployer.java:281)
	at org.mobicents.slee.container.deployment.jboss.SleeContainerDeployerImpl.start(SleeContainerDeployerImpl.java:271)
	at org.mobicents.slee.container.deployment.jboss.SLEEDeployer.callSubDeployer(SLEEDeployer.java:124)
	at org.mobicents.slee.container.deployment.jboss.SLEEDeployer.setInternalDeployer(SLEEDeployer.java:170)
	at org.mobicents.slee.container.deployment.jboss.SleeContainerDeployerImpl$1.run(SleeContainerDeployerImpl.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
17:06:40,662 WARN  [SleeContainerDeployerImpl] (SLEE-InternalDeployer-thread-1) SLEE DUs not deployed, due to error(s):
file:/opt/restcomm-smsc-7.3.153/jboss-5.1.0.GA/server/simulator/deploy/smsc-services-du-7.3.153.jar/

**Comment by MaabSaleeem** [comment]
@faizann @vetss

**Comment by gsaslis** [comment]
@MaabSaleeem could you please help us understand a little more about when this is happening?

Can you please provide: 

* steps to reproduce and 
* some more complete logs (using [GitHubGist](https://gist.github.com/) )?

Thanks in advance!

**Comment by olenara** [comment]
@MaabSaleeem this is related to Java version. SMSC should be run with Java 7 version.
