### ISSUE TITLE
Possible unbind() and close() Exception

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#54]
When SMSC GW is unbinding / closing SMPP connection then it may occurs that the base TCP connection is already down. This leads the Exception that is not caught and next "close() / destroy()" method is not invoked. 

This leads than this ESME will not start again.

found methods for this case:
SmppClientManagement.stopSmppClientSession(Esme esme)
EsmeManagement.stopWrappedSession(Esme esme)

we need to find out also ALL methods with "close()" and "unbind()" in smpp part and 
enclose them with try - catch section with just logging.

**Comment by vetss** [comment]
https://telestax.zendesk.com/agent/tickets/33048

**Comment by vetss** [comment]
This is the Exception:

2016-03-14 10:15:15,311 ERROR [org.mobicents.smsc.smpp.SmppClientOpsThread] (Thread-52) Exception while trying to send ENQUIRE_LINK for ESME SystemId=tiscubi
com.cloudhopper.smpp.type.SmppChannelException
        at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestPdu(DefaultSmppSession.java:535)
        at com.cloudhopper.smpp.impl.DefaultSmppSession.sendRequestAndGetResponse(DefaultSmppSession.java:464)
        at com.cloudhopper.smpp.impl.DefaultSmppSession.enquireLink(DefaultSmppSession.java:439)
        at org.mobicents.smsc.smpp.SmppClientOpsThread.enquireLink(SmppClientOpsThread.java:169)
        at org.mobicents.smsc.smpp.SmppClientOpsThread.run(SmppClientOpsThread.java:138)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at com.cloudhopper.smpp.channel.SmppSessionLogger.handleDownstream(SmppSessionLogger.java:110)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:334)
        at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.close(Channels.java:812)
        at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)
        at com.cloudhopper.smpp.impl.DefaultSmppSession.close(DefaultSmppSession.java:414)
        at com.cloudhopper.smpp.impl.DefaultSmppSession.unbind(DefaultSmppSession.java:400)
        at org.mobicents.smsc.smpp.SmppClientManagement.stopSmppClientSession(SmppClientManagement.java:136)
        at org.mobicents.smsc.smpp.EsmeManagement.stopWrappedSession(EsmeManagement.java:382)
        at org.mobicents.smsc.smpp.EsmeManagement.stopEsme(EsmeManagement.java:367)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
        at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
        at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
        at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
        at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
        at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:98)
        at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
        at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:87)
        at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:139)
        at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:101)
        at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:90)
        at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:377)
        at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:147)
        at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:195)
        at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
        at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:293)
        at org.jolokia.http.AgentServlet.handle(AgentServlet.java:225)
        at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:190)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
        at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
        at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
        at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
        ... 1 more
2016-03-14 10:15:15,386 INFO  [com.cloudhopper.smpp.impl.DefaultSmppSession] (http-10.39.25.42-8080-4) Successfully closed

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/9056810e2f167b1c4884e538457123f77b8a9c1d
https://github.com/RestComm/smscgateway/commit/5331952e16d4522422b05eda234d09c43ebe2adb
