### ISSUE TITLE
Exception when creating of delivery receipt in case of a message validity period expire

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#57]
2016-03-17 09:39:15,118 ERROR [javax.slee.RAEntityNotification[entity=SchedulerResourceAdaptor].SchedulerResourceAdaptor] (pool-59-thread-1) Exception when runn
ung injectSmsOnFly() for receipt in doInjectSmsDatabase(): Transaction Mandatory
javax.slee.TransactionRequiredLocalException: Transaction Mandatory
        at org.mobicents.slee.runtime.transaction.SleeTransactionManagerImpl.mandateTransaction(SleeTransactionManagerImpl.java:121)
        at org.mobicents.slee.resource.SleeEndpointImpl.startActivityTransacted(SleeEndpointImpl.java:253)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor.doInjectSms(SchedulerResourceAdaptor.java:779)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor.doInjectSmsOnFly(SchedulerResourceAdaptor.java:522)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor$1.injectSmsOnFly(SchedulerResourceAdaptor.java:92)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor.doInjectSmsDatabase(SchedulerResourceAdaptor.java:707)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor.onTimerTick(SchedulerResourceAdaptor.java:454)
        at org.mobicents.smsc.slee.resources.scheduler.SchedulerResourceAdaptor$TickTimerTask.run(SchedulerResourceAdaptor.java:334)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
This issue is because:
generating of delivery receipts after a message validity period is expired in Schedule RA processing was treated as processing from SBB but not from RA. This leads the Exception.
Another bad thing is that for some time after this any new message sending to this destination address is blocking (messages are dropped)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/bfd265ab18c1306b7f1d9ef1032f71ae65f1e9f9
