### ISSUE TITLE
PersistenceResourceAdaptorisDatabaseAvailable() - NullPointerException

### ISSUE THREAD

**Issue by vetss** [RestComm/smscgateway#64]
We can have NullPointerException in this module in startup time when "dbOperations_C2" has not been specified.
We need to check for null and return error in this case.

**Comment by vetss** [comment]
2016-03-22 10:48:15,916 ERROR [org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl] (pool-52-thread-1) Caught exception while routing EventC
ontext[event type id = EventTypeID[name=ss7.map.service.sms.ALERT_SERVICE_CENTER_REQUEST,vendor=org.mobicents,version=1.0] , event = AlertServiceCentreRequestWr
apper [wrapped=AlertServiceCentreRequest [DialogId=9, msisdn=ISDNAddressString[AddressNature=international_number, NumberingPlan=ISDN, Address=393397552412], se
rviceCentreAddress=ISDNAddressString[AddressNature=international_number, NumberingPlan=ISDN, Address=393110456789]]] , local ac = RA:MAPRA:MAPDialogActivityHand
le(id=9) , address = IP: localhost , serviceID = null]
java.lang.NullPointerException
        at org.mobicents.smsc.slee.resources.persistence.PersistenceResourceAdaptor$1.isDatabaseAvailable(PersistenceResourceAdaptor.java:90)
        at org.mobicents.smsc.slee.services.alert.AlertSbb.setupAlert(AlertSbb.java:219)
        at org.mobicents.smsc.slee.services.alert.AlertSbb.onAlertServiceCentreRequest(AlertSbb.java:204)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
        at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:379)
        at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:126)
        at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smscgateway/commit/5fafe5e3a472399886a925e6d8d0853ca6b26d15
